### ISSUE TITLE
Possible problem in code with regards to adding modules

### ISSUE THREAD

**Issue by tzzzening** [AY1920S2-CS2113-T15-3/tp#12]
Hello, at this point we have yet to confirm whether we will be providing students with a list of modules that they need to clear, or whether the students will be inputting the modules by themselves. Let's assume that we will be doing the latter since the code supports that function.

From what I see, I think there may be an issue in the code when the student adds modules. This is because the student can input either the module code or the module name into the system. The problem comes when the student adds the module code and module name of the same module at different instances. Instead of one single module with a module code and a module name, it becomes 2 separate modules.

I am saying this largely based on the `private static AddCommand processAddCommand(String args)` method in the `Parser` class.

Perhaps the code is not complete, or the `processAddCommand` is just processing modules that are being added to the list of modules that the student has completed instead of the at the beginning when the student adds to the full list of modules that he needs to clear.

Please correct me if I am wrong, and thanks in advance.

**Comment by tzzzening** [comment]
Okay this is irrelevant already

**Comment by DeetoMok** [comment]
We have decided to prepare the modules that are applicable to students in computer science course. Thus the modules will be pre determined
